---
baseurl: "http://remitt.org"
languageCode: "en-us"
title: "REMITT"
description: "Opensource Electronic Medical Billing"
copyright: "Copyright (c) 1999-2014 FreeMED Software Foundation"
permalinks:
  post: /:year/:month/:title/
params:
  github: freemed/remitt
  twitter: "remitt"
  GitHubUser: "freemed"
...
