baseurl = "http://remitt.org/"
languageCode = "en-us"
title = "REMITT"
theme = "github-project-landing-page"

[params]
  description = "REMITT Electronic Medical Information Translation and Transmission"
  author_url = "http://github.com/freemed"
  project_url = "http://github.com/freemed/remitt"
  project_documentation = "http://github.com/freemed/remitt/wiki"
  github_project_name = "remitt"
  github_user_name = "freemed"
  twitter_url = "http://twitter.com/jbuchbinder"

  first_color="#f8f8f8"
  first_border_color="#e7e7e7"
  first_text_color="#333"

  second_color="white"
  second_text_color="#333"

  header_color="#f8f8f8"
  header_text_color="rgb(51, 51, 51)"

  header_link_color="#777"
  header_link_hover_color="rgb(51, 51, 51)"

